samples/server/go-server/api/server/storage/memstore.go
samples/server/go-server/api/server/v1alpha1/impl.go
server-go/storage.go

Based on the memstore sample, provide a golang interface for how to
interact with a storage implementation.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

*: provide a storage interface

---

v1alpha1/grafeas.json

* found while reading the schema.
Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Fix minor typos

---

samples/server/go-server/api/artifact.go

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

Fix minor typo

---

samples/server/go-server/api/server/Dockerfile

Specifically I wanted this so I could easily run on a different port

Dockerfile

---

config.yaml.sample
samples/server/go-server/api/server/config/config.go
samples/server/go-server/api/server/storage/memstore.go
samples/server/go-server/api/server/storage/pgsqlconfig.go
samples/server/go-server/api/server/storage/pgsqlstore.go
samples/server/go-server/api/server/storage/pgsqlstore_test.go
samples/server/go-server/api/server/storage/queries.go
samples/server/go-server/api/server/storage/storager_test.go
samples/server/go-server/api/server/v1alpha1/impl.go
samples/server/go-server/api/server/v1alpha1/impl_test.go
server-go/storage.go
vendor/github.com/fernet/fernet-go/License
vendor/github.com/fernet/fernet-go/Readme
vendor/github.com/fernet/fernet-go/fernet.go
vendor/github.com/fernet/fernet-go/generate.json
vendor/github.com/fernet/fernet-go/invalid.json
vendor/github.com/fernet/fernet-go/key.go
vendor/github.com/fernet/fernet-go/verify.json
vendor/vendor.json

Squashed and rebased version of #111
Question to reviewers: I've defaulted the page size to 100 for requests that does not specify page size. Sounds reasonable?

Pagination support for projects, notes, occurrences and operations

---

v1beta1/proto/grafeas.proto

Adding HTTP bindings for batch create methods and adding missing BatchCreateOperations.

---

v1beta1/proto/grafeas.proto

Fixing incorrect body for create and update operation.

Fixing incorrect body for create and update operation.

---

v1beta1/proto/grafeas.proto

Updating batch create notes and operations to use maps.

updating batch creates to use maps

---

v1beta1/proto/grafeas.proto

update GetVulnerabilityOccurrencesSummary to show fixable/total by

---

v1beta1/proto/grafeas.proto

We don't have a good use for operations.

removing the operation RPCs

---

v1alpha1/proto/grafeas.swagger.json

added title, version, and license info to v1alpha1 swagger spec

Swagger Metadata

---

v1beta1/proto/grafeas.proto

Updating required and immutable fields for notes and occurrences.

documentation updates for notes and occurrences

---

v1beta1/proto/provenance.proto

remove references to GCS, make source more generic

---

samples/server/go-server/api/server/storage/pgsqlconfig.go
samples/server/go-server/api/server/storage/pgsqlstore_test.go

Allow omitting username in config

---

Makefile

the include folder doesn't exist and make complains, remove it

remove include folder

---

v1beta1/proto/vulnerability.proto

When these messages are used as inputs to the API these fields are required to be set.

marking some required fields for vuln msgs

---

samples/server/go-server/api/server/api/api.go

Enables running a secure standalone grafeas deployment without TLS
Signed-off-by: Liron Levin <liron@twistlock.com>

Support running grafeas server with unix socket

---

README.md

Updated formatting of resource URL examples

---

proto/v1beta1/vulnerability.proto

to Occurrences, Notes, and appearances of vulnerabilities.

Updated some comments to disambiguate references

---

README.md

It will be deleted after the PR is merged.

Merged the About section from grafeas.io

---

proto/v1beta1/attestation.proto

This is now consistent with the actual proto definition.

Updated v1beta1.GenericSignedAttestation comment

---

proto/v1/grafeas_go_proto/grafeas.pb.go
proto/v1/grafeas_go_proto/grafeas.pb.gw.go
proto/v1/project_go_proto/project.pb.go
proto/v1/project_go_proto/project.pb.gw.go
proto/v1beta1/grafeas_go_proto/grafeas.pb.go
proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go
proto/v1beta1/project_go_proto/project.pb.go
proto/v1beta1/project_go_proto/project.pb.gw.go
proto/v1beta1/swagger/grafeas.swagger.json
proto/v1beta1/swagger/project.swagger.json
v1alpha1/proto/grafeas.pb.go
v1alpha1/proto/grafeas.pb.gw.go
v1alpha1/proto/grafeas.swagger.json

Updated swagger specs and service definitions with latest protoc

---

proto/v1/package.proto

Adding a canonicalVersion string to the Version proto.

proto change for canonicalversion

---

go/v1/api/occurrence_test.go
go/v1/api/validators/grafeas/grafeas.go
go/v1/api/validators/grafeas/grafeas_test.go
proto/v1/grafeas.proto

The Resource composite type is confusing and probably not needed for now. Reverting it to a resource_uri string.

changing Resource composite type to just a resource_uri string

---

Dockerfile
docs/grafeas_image.md

Added instructions on building and pushing the image.

Updated Grafeas server image

---

samples/server/go-server/api/server/storage/embeddedstore.go
samples/server/go-server/api/server/storage/memstore.go
samples/server/go-server/api/server/storage/pgsqlstore.go
samples/server/go-server/api/server/storage/storager_test.go
server-go/storage.go

Specifically, removed endpoints with Operation, which is an obsolete concept from `v1alpha` API.
The following PR will update the location of the server code and the Dockerfile to generate image with the Grafeas server.

Updated Grafeas server implementation

---

proto/v1/common.proto
proto/v1/generate.go
proto/v1/grafeas.proto
proto/v1/upgrade.proto

This type represents a available software upgrade for a given resource
url. It is complementary to the package and vulnerability types.

v1: Add upgrade occurrence and note type.

---

CHANGELOG.md
RELEASING.md
grafeas-charts/README.md
grafeas-charts/values.yaml

Added CHANGELOG for `0.1.0` as well.

Added instructions on releasing Grafeas helm chart

---

Dockerfile

Fixed Dockerfile to perform `make build` before building the server

---

proto/v1/vulnerability.proto

This was supposed to be under vulnerability, not windowsDetail

Fix v1 source_update_time field.

---

go/v1beta1/storage/embeddedstore.go
go/v1beta1/storage/memstore.go
go/v1beta1/storage/pgsqlstore.go
go/v1beta1/storage/queries.go
go/v1beta1/storage/storage_test.go
go/v1beta1/storage/testobjects.go

This addresses #157. Also, ensured everything is now fixed for #247.

Grafeas storage generates IDs for Occurrences

---

docs/running_grafeas.md

Updating docs with new tag version

---

CHANGELOG.md
grafeas-charts/values.yaml

v0.1.1 release

---

go/v1beta1/server/server.go

Hello @aysylu !
This will fix the issue from #389 :)

Rest endpoint fix 

---

CHANGELOG.md
grafeas-charts/Chart.yaml
grafeas-charts/values.yaml

v0.1.4 release

---

proto/v1/upgrade.proto

Fixing the proto message name

---

Dockerfile

Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>

bumped to golang 1.14.0

---

CHANGELOG.md
grafeas-charts/Chart.yaml
grafeas-charts/values.yaml

* Added support for in-toto.
* Added JWT support to attestation notes.

v0.1.6 release

---

go/v1/api/validators/attestation/attestation.go

This update attestation validation to handle jwts.

Update attestation validation to handle jwts.

---

go/v1beta1/storage/pgsqlstore.go
go/v1beta1/storage/pgsqlstore_test.go

pgsqlstore: Minor code clean up

---

proto/v1/common.proto
proto/v1alpha1/grafeas.proto
proto/v1alpha1/swagger/grafeas.swagger.json
proto/v1beta1/common.proto
proto/v1beta1/common_go_proto/common.pb.go

This PR adds missing descriptions in protos which were missing in https://github.com/grafeas/grafeas/pull/466.

Improved description of unspecified note kind

---

proto/v1/vulnerability.proto

Add the vendor info to the V1 api.

Add the vendor info to the V1 api.

---

proto/v1/intoto_provenance.proto

Renamed Builder to BuilderConfig, to not conflict with the Java generated Builder class.

Renamed Builder to BuilderConfig

---

proto/v1/dsse_attestation.proto
proto/v1/grafeas.proto

Originally we had DSSEAttestationNote and DsseAttestationOccurrence. Making them both DSSE.

Make casing of dsse consistent

---

go/v1/api/validators/build/build.go
go/v1/api/validators/build/build_test.go

Either provenance or intotoprovenance is mandatory.

Make provenance optional

---

grafeas-charts/Chart.yaml
grafeas-charts/values.yaml

This is a leftover configuration change from the last release.

Updated helm charts version to v0.2.1

---

CHANGELOG.md
grafeas-charts/Chart.yaml
grafeas-charts/values.yaml

Closes  #534
Will need an admin to tag the release.

Release v0.2.1

---

CHANGELOG.md
grafeas-charts/Chart.yaml
grafeas-charts/values.yaml

- SBOM enhancements.
- SLSA enhancements.
- Vex Assessment enhancements.

Release v0.2.3
