samples/server/go-server/api/server/errors/errors.go, samples/server/go-server/api/server/handler.go, samples/server/go-server/api/server/name/name.go, samples/server/go-server/api/server/storage/memstore.go, samples/server/go-server/api/server/v1alpha1/impl.go, server-go/errors/errors.go, server-go/storage.go
Also have AppError satisfy the builtin errors so it can be bubbled up.
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> errors: top-level error type

samples/server/go-server/api/note.go, samples/server/go-server/api/occurrence.go
The sample Grafeas server no longer ignores the AttestationAuthority
type when creating Note objects or the Attestation type when creating
Occurrence objects.
=> Add missing AttestationAuthority and Occurrence types

Makefile
generated pb.go is not in ./model-go/
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>
=> Makefile: target is in wrong directory

Dockerfile
I propose that the Dockerfile uses local source files instead of go get:ing them from the official repo. This makes it easier to build docker images during development and in forks.
Note that the Dockerfile was moved as well to allow docker to access the complete source tree.
CC @lizrice
=> Copy local files instead of go get:ing in Dockerfile

config.yaml.sample, docs/running_grafeas.md, samples/server/go-server/api/server/api/api.go, vendor/github.com/rs/cors/LICENSE, vendor/github.com/rs/cors/README.md, vendor/github.com/rs/cors/cors.go, vendor/github.com/rs/cors/utils.go, vendor/vendor.json
This adds support for Cross-Origin Resource Sharing to the sample service to make it easier to develop browser-based applications agains the grafeas API.
=> Add CORS support to sample app.

samples/server/go-server/api/server/config/config.go
Modified code to ignore postgres settings when storage type is memstore, this allows removing postgres setting from config file when not used or will generate runtime error "invalid memory address or nil pointer dereference"
=> Modified code to ignore postgres settings when storage type is memstore

v1beta1/proto/discovery.proto
The details of an error are stored in `analysis_status_error`.
=> Remove UNSUPPORTED_RESOURCE option for AnalysisStatus

v1beta1/proto/project.proto
Fixed leftover v1alpha1 when forking. Renamed service to  just "Projects", dropping the "Grafeas" prefix.
=> fix v1alpha -> v1beta1 and rename service

v1beta1/proto/grafeas.proto
We don't have a good use for operations right now.
=> removing operation_name from notes and occurrences

v1beta1/proto/grafeas.proto
Include version in Grafeas service name to make it easier to serve multiple versions of the API from the same binary if desired.
=> include version in Grafeas service name

samples/server/go-server/api/server/config/config.go
Fixes https://github.com/grafeas/grafeas/issues/166 by changing the
defaultConfig to serve on `0.0.0.0` instead of `localhost`
Signed-off-by: Jonathan Pulsifer <jonathan@pulsifer.ca>
=> [sample server] expose Grafeas on 0.0.0.0

Dockerfile
:wave: hi friends
- bumping go
- removing trailing whitespace
```sh
~/src/github.com/jonpulsifer/grafeas (bump-go) $ docker run -d --rm -p 8080:8080 grafeas
~/src/github.com/jonpulsifer/grafeas (bump-go) $ curl localhost:8080/v1alpha1/projects
{"projects":[],"nextPageToken":"0"}
```
=> [Dockerfile] bump golang and remove trailing whitespace

Makefile
The v1alpha1/proto/grafeas.pb.go target does not run its recipe again after an initial run since the target file and its prereqs always exist. The phony target that runs v1alpha1/proto/grafeas.pb.go doesn't work the way we intend, so make the protoc recipe a phony target.
=> fix grafeas_go phony target

v1beta1/proto/grafeas.proto
after removing kind, we shouldn't regress the next_id value
=> next_id for ListOccurrencesRequest back to 7

v1beta1/proto/package.proto
When these messages are used as inputs to the API these fields are required to be set.
=> marking some required fields for pkg msgs

samples/server/go-server/api/server/storage/embeddedstore.go, samples/server/go-server/api/server/storage/memstore.go, samples/server/go-server/api/server/storage/pgsqlstore.go, samples/server/go-server/api/server/storage/queries.go, samples/server/go-server/api/server/storage/storager_test.go
According to protobuf specification, the next token should be empty for
the last.
```go
// The next pagination token in the list response. It should be used as
// page_token for the following request. An empty value means no more result.
NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
```
Signed-off-by: Liron Levin <liron@twistlock.com>
=> Return empty page token for last response

server-go/filtering/common/errors.go
Found using https://go-critic.github.io/overview#unslice-ref
=> Simplify s[:] to s where s is a slice

samples/server/go-server/api/server/testing/testobjects.go, samples/server/go-server/api/server/v1alpha1/impl.go, samples/server/go-server/api/server/v1alpha1/impl_test.go
Add missing beta APIs for batch updates.
The current implementation reuses the storage APIs without doing a bulk
storage update.
If you think it is needed we can re-implement this code per storage
provider.
Signed-off-by: liron <liron@twistlock.com>
=> Add batch APIs for notes and occurrences

docs/grafeas_concepts.md
This is also fixable by changing `<Checksum>` to `checksum` and avoiding markdown code blocks, although code blocks are clearer IMHO.
Also fixed in Grafeas docs https://github.com/grafeas/grafeas.github.io/pull/19
---
FWIW I fixed this in March, but suspect that the repo docs were pasted into the website, so have now updated both https://github.com/grafeas/grafeas.github.io/pull/5
=> docs: fix markdown rendering

samples/server/go-server/api/server/api/api.go
The wrong path is used to generate the TLS settings (leads to client connectivity problems).
Signed-off-by: liron <liron@twistlock.com>
=> Fix TLS registration

proto/v1beta1/common.proto
This change just adds the `Signature` message and specification comments.  Future updates will make use of signatures in `Attestation`.
=> Add Signature message to v1beta common.proto.

proto/v1/discovery.proto
Short explanation: it doesn't make sense for the Discovery to be analyzed at a subsequent time. So we can just remove this field.
=> Removed Discovery's last_analysis_time field as it's not needed.

proto/v1/deployment.proto, proto/v1/grafeas.proto, proto/v1/provenance.proto, proto/v1/vulnerability.proto
We follow semantic versioning in Grafeas and breaking changes require a new API version (which means a new set of protos, so we can reset the numbering any way we want), so we don't have to worry about reserving proto tag values.
=> remove the "next_id" comments in protos

go/name/name.go
Clarifying name parsing error messages to include the resource the name is for. Also switched to using double quotes for the expected resource name format to be more inline with Go style.
=> clarifying name parsing error messages to include the resource the name is for

go/v1beta1/README.md, go/v1beta1/config.yaml
Added the `config.yaml` file to be used as example.
=> Fixed instructions for how to run the server with config

cloudbuild_release.yaml, grafeas-charts/Dockerfile
1. Added `apt-get update` to the CloudBuild config;
1. Added executable permissions on the script that's run by the grafeas helm release container.
=> Fixed CD flow for Grafeas helm chart

proto/v1/vulnerability.proto, proto/v1beta1/swagger/grafeas.swagger.json, proto/v1beta1/vulnerability.proto
This is used to indicate when the source last changed, for latency
considerations and because CreateTime and UpdateTime are grafeas
specific.
=> Create source timestamp fields.

.circleci/config.yml, Dockerfile_helm_release, cloudbuild_release.yaml, grafeas-charts/Dockerfile
1. Moved `grafeas-charts/Dockerfile` to `./Dockerfile_helm_release`, for consistency of executing `docker build` on CircleCI and CloudBuild.
1. Removed (for now) testing on CircleCI of the helm deploy Dockerfile, as we'll be moving towards shared testing infrastructure in Grafeas and Kritis, and will potentially move away from CircleCI, at which point the `docker build` will be re-added for this file.
=> Deploy through CloudBuild fixes

Dockerfile_helm_release
Latest CloudBuild run failed to run the script with:
```
time="2019-07-24T22:42:35Z" level=error msg="error waiting for container: context canceled"
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"./grafeas-charts/helm_release.sh\": permission denied": unknown.
Already have image: us.gcr.io/grafeas/helm-release:v0.1.0
```
Also, removed debugging statements.
=> Added chmod +x to make the helm_release.sh executable

proto/v1/discovery.proto
This is extremely useful for figuring out the operating system of a
resource without having to rely on sub occurrences which may not exist.
=> Add CPE to the discovery occurrence for V1.

go/v1/filter/filter.go
Why does GitHub have a title and a description for a PR, all you need is a description, titles are annoying.
=> Remove list method specific comments from filter infra as non-list methods may have filters.

grafeas-charts/templates/secrets.yaml, grafeas-charts/values.yaml
These changes are to easily allow the use of an existing generated secret and certs instead of generating them with the helm chart.
=> support for both existing and creation of secret for helm chart

proto/v1/vulnerability.proto
It can be resolved at occurrence creation time from the note information and hence filled in during occurrence creation by the API.
=> Effective severity should be output only.

proto/v1/vulnerability.proto
It's not clear it should be output only.
=> Reverting output only comment on effective severity for now.

proto/v1beta1/grafeas.proto
This PR adds the API client config annotations per aip.dev, based on the [v1beta1/containeranalysis_gapic.yaml](https://github.com/googleapis/googleapis/blob/5af83f47b9656261cafcf88b0b3334521ab266b3/google/devtools/containeranalysis/v1beta1/containeranalysis_gapic.yaml). These annotations are used by client library generators to generate API client libraries. They are replacing the GAPIC config yaml file.
@vtsao this is the follow up PR to the internal CL.
=> Add API config annotations

proto/v1/grafeas.proto
Adds API client config annotations per aip.dev, based on the [v1/grafeas_gapic.yaml](https://github.com/googleapis/googleapis/blob/5af83f47b9656261cafcf88b0b3334521ab266b3/grafeas/v1/grafeas_gapic.yaml). These options are used for client library generation.
CC: @vtsao
=> Add API client config annotations to v1

proto/v1/discovery.proto
For things that are not continuously analyzed, it is valuable to report the last time a scan occurred.
=> add last_scan_time to discovery occurrences

proto/v1/grafeas.proto, proto/v1/project.proto
As pointed out by https://github.com/googleapis/google-cloud-dotnet/issues/4102, Grafeas should not use the Google-specific Project resource definition, but rather its own. cc @jskeet
This annotates the `Project` message with the resource definition, adds resource references to GetProjectRequest and DeleteProjectRequest, and changes references of `cloudresourcemanager.googleapis.com/Project` to `grafeas.io/Project`.
=> add resource annotation to Project

.circleci/config.yml
…QL requiring a password.
https://discuss.circleci.com/t/postgresql-image-password-not-specified-issue/34555
=> Fixed CircleCI build that was failing due to newer images of PostgreSQL requiring a password.

go/v1beta1/storage/pgsqlstore.go, go/v1beta1/storage/pgsqlstore_test.go, go/v1beta1/storage/storage.go, go/v1beta1/storage/storagefactory.go
Automatic generation of pagination key had been implemented in the past, but got removed during some refactoring. https://github.com/grafeas/grafeas/blob/cd06912f00d1f23b49ecb82f39e9283625b6ec87/go/config/config.go#L79
As an alternative we could make the pagination key a required field in the configuration file: 
https://github.com/grafeas/grafeas/blob/master/go/v1beta1/config.yaml#L33 but that seems heavy-handed.
=> Generating pagination key when one is not provided by the configuration.

grafeas-charts/templates/configmap.yaml, grafeas-charts/templates/deployment.yaml, grafeas-charts/values.yaml
This PR is a partial restructure of the Grafeas helm chart and includes the following:
* Additional comments and references 
* Moving of fields under `persistence` field
* Option to disable `persistence` which will not create and PVs or PVCs other that config
For restricted environments, it's not inherently easy for the creation of PV and PVCs. The option to disable PVs and PVCs is a common one for many helm charts.
Open to thoughts and suggestions.
=> chore(chart): update helm chart for option to disable persistence

go/v1/api/validators/attestation/attestation.go, go/v1/api/validators/attestation/attestation_test.go
The spec (protobuf) specifies that keys MUST be RFC3986 conformant. This
patch adds a validator to ensure this.
=> Validate public key IDs use an RFC3986 conformant

docs/running_grafeas.md
- Docker build may fail due to kernel bug, we need to bypass it with Wiktor's command.
- GOPATH needs to be set explicitly in the terminal
- Secure connection. In the previous doc, server runs without cert but client tests with cert, so there would be SSL error. To fix this, server needs to run with cert and client tests with cert. Alternatively, both server/client get rid of cert.
=> improvement of doc for beginners

go/v1/api/validators/attestation/attestation.go, go/v1/api/validators/attestation/attestation_test.go
Reverts grafeas/grafeas#432
This change breaks backwards compatibility and was based on inaccurate documentation.
1. The key IDs stored by Binauthz are unfortunately not in this format. To include this change, Binauthz would either need to backfill our database or edit key IDs on the fly as we retrieve them from the database. Other users of Grafeas will likely run into similar issues.
2. Patrick Lawson originally wrote this documentation, and I've confirmed with him that "public key ID MUST be RFC3986 conformant" is an error. It should read "public key ID SHOULD be
RFC3986 conformant". I'll update the documentation after this rollback is approved.
=> Revert "Validate public key IDs use an RFC3986 conformant"

go/v1/api/occurrence_test.go, go/v1beta1/api/occurrence_test.go
Updating each test case to run as a subtest makes the output clearer. This is most apparent in test cases that log errors; when all cases run as a single test, the output contains the log statements from all cases.
I came across this while making some changes that required updating these tests; submitting as a separate PR as it's completely separate.
=> Use subtests in occurrence_test

go/v1/api/occurrence_test.go, go/v1beta1/api/occurrence_test.go
The TestUpdateOccurrenceErrors currently rely on the fact that we check for an existing occurrence last.
For example, if writing to the the storage layer is erroring *and* there is no existing occurrence, the test is asserting that we return the storage error, which seems overspecified.
Update the tests so that there is an existing occurrence in the database for the test cases that are exercising other error paths.
The one exception is that it is important to return a permission error instead of a NotFound error if the user doesn't have the required permission (to avoid leaking the existence of a resource they don't have permission to see). I've added a test case to specifically validate that case. (The code is correct here, the test is just ensuring we are specifically testing that …
=> Make occurrence update tests less dependent on implementation details

proto/v1beta1/swagger/grafeas.swagger.json
Provide a better description `NOTE_KIND_UNSPECIFIED`,  that is never actually used, but `NoteKind` always a required field.
=> Improves description of NOTE_KIND_UNSPECIFIED

go/v1/api/grafeas_test.go, go/v1/api/occurrence.go, go/v1/api/occurrence_test.go, go/v1beta1/api/grafeas_test.go, go/v1beta1/api/occurrence.go, go/v1beta1/api/occurrence_test.go
* Add tests on permission checking
Add some tests to validate the permission checks on UpdateOccurrence operations. To support the tests, add a allowListAuth test implementation of Auth that just stores a list of allowed project/permission pairs.
Two of the tests are documenting incorrect behavior that is fixed in a later commit. Namely:
(1) Updating the NoteName should require NotesAttachOccurrence on the old NoteName (as this is effectively a detach operation).
(2) When excluding the NoteName from the update using an UpdateMask, the permission check should be performed against the existing NoteName, not whatever was passed in (and which will be ignored).
* Fix permission checks in occurrence update function
This commit fixes the permission checks in UpdateOccurrence and updates the …
=> Fix permission checks in occurrence update function

docs/running_grafeas.md
The instructions for using the curl command with the certificate didn't work for me.  I got the error message: 
`curl: (58) unable to set private key file: 'server.pem' type PEM`
When I added these additional flags, it worked fine.
=> Update to curl flags with certificate

proto/v1beta1/vulnerability.proto
Add the vendor field to Vulnerability.Detail, which is necessary to differentiate between products of the same name in the NVD 1.1 feed.
=> Add the vendor field to Vulnerability.Detail

go/v1/api/grafeas.go, go/v1/api/grafeas_test.go
Current limit is unnecessarily restrictive.
=> Increase max page size in v1 API: 1k -> 10k.

README.md
Hello! 👋 
A while ago I opened #470 to get some feedback on a new backend we've been working on based on Elasticsearch.  That didn't seem to get much attention, but we've been contributing more and more to this project, and we feel comfortable enough in it to have it listed in this README, if you're willing to merge this PR :smile:
We'll continue to add more features to this backend and support it long term, as it's an important part of a software supply chain project we're in the middle of working on.
Thanks!
=> add grafeas-elasticsearch to list of backends

docs/json_examples/note_build.json, docs/json_examples/note_deployment.json, docs/json_examples/note_vulnerability.json, go/v1beta1/example/client/client.go
Updates to documentation as per https://github.com/grafeas/grafeas/issues/246
I've updated the json examples as per previous PR feedback.
I've also extended the grpc client example code to create notes and occurrences. Appreciate this is a long method but seemed most appropriate to leave it like this with comments than split into smaller functions.
=> updating json examples and extended the grpc client example

README.md
Hi Grafeas Team,
This is the Paranoids Engineering Team from Yahoo. We implemented a new storage backend for AWS RDS (https://github.com/theparanoids/grafeas-rds) as a part of our new Software Supply Chain project. Can you give us some feedback? And if possible, can you add this project link to the readme?
Thank you!
=> Add grafeas-rds to list of backends.

proto/v1/intoto_provenance.proto
Java clients that are generated from these protos fail to build due to the mismatch between the name of the proto message and the name of the file. Specifically, the filename will be converted to `IntotoProvenance` while the actual message is `InTotoProvenance`. This is causing downstream issues: https://github.com/googleapis/java-grafeas/pull/410
This PR resolves this issue by setting the Java name explicitly.
=> add java_outer_classname to intoto to avoid java client generation failures

cel/syntax.pb.go, go.mod, go.sum, proto/v1alpha1/grafeas.proto, proto/v1alpha1/swagger/grafeas.swagger.json, proto/v1beta1/grafeas_go_proto/grafeas.pb.gw.go, proto/v1beta1/project_go_proto/project.pb.gw.go, proto/v1beta1/swagger/grafeas.swagger.json, proto/v1beta1/swagger/project.swagger.json, tools/go.mod, tools/go.sum
Fixes #379
grpc-gateway recently updated to replace google.api.http paths with ones that meet the openapi specification.
see: 
https://github.com/grpc-ecosystem/grpc-gateway/pull/2461
https://github.com/grpc-ecosystem/grpc-gateway/pull/2496
One thing to note: grpc-gateway doesn't always (yet?) group operations in the same meaningful way that was intended in the proto file. This impacts the v1alpha1 grafeas.swagger.json in a small way, and was mitigated a bit more by reordering the grafeas.proto file.
=> Updates grpc-gateway@v2.7.3

grafeas-charts/templates/secrets.yaml
When trying to run helm install or helm upgrade with the  `--set secret.enabled=true` switch no secrets were being created. I used the same format for evaluation of truthy values as used in the configmap template and it works.
=> Fixed issue with boolean evaluation on command line value switch truthy

proto/v1/compliance.proto
This field will be used to store a reference to the document that defines the given benchmark, making it easier for product teams to look up information about compliance findings. For most OSes, each CPE URI will have a corresponding benchmark document.
=> Add a "benchmark_document" field to the compliance proto.

go/filtering/common/source_test.go
`go vet` (go1.18) fails currently.
```
> go version
go version go1.18 darwin/amd64
> go vet ./...
go/filtering/common/source_test.go:128:3: (*testing.common).Error call has possible formatting directive %d
go/filtering/common/source_test.go:130:3: (*testing.common).Error call has possible formatting directive %s
```
This pr fixes it.
=> Fix go1.18 vet error: (*testing.common).Error call has possible formatting directive.

go.mod, go.sum
Prior to this commit, the version of a dependency package called [`in-toto-golang`](https://github.com/in-toto/in-toto-golang) we use is v0.4.0-prerelease but there is a [bug](https://github.com/in-toto/in-toto-golang/blob/7f8ae9c3c60b5a6ab8ab3df2fb414dae22a4d30b/in_toto/model.go#L1036-L1042) in this version.
In this commit, we change to a stable version of `in-toto-golang` package.
=> Update in-toto-golang version

go/v1beta1/api/note.go, go/v1beta1/api/note_test.go
This is adding a new validation rule on NoteID in createNote to avoid using / as a part of NoteID.
=> Fixed issue #558 to return error when createNote with slash in NoteID
